### ISSUE TITLE
Extensions should not make HTTP requests in the Swing event dispatch thread on burp 1.6.17 when send request to autorize

### ISSUE THREAD

**Issue by johnniesong** [Quitten/Autorize#1]
java.lang.RuntimeException: java.lang.RuntimeException: Extensions should not make HTTP requests in the Swing event dispatch thread
	at burp.my.a(Unknown Source)
	at burp.tyg.makeHttpRequest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:496)
	at org.python.core.PyObject.__call__(PyObject.java:500)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.makeRequest$27(D:\Chrome\burpsuite_pro_v1.6.17\bapps\f9bbac8c4acf4aefa4d7dc92a991af2f\Autorize.py:519)
	at org.python.pycode._pyx1.call_function(D:\Chrome\burpsuite_pro_v1.6.17\bapps\f9bbac8c4acf4aefa4d7dc92a991af2f\Autorize.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.checkAuthorization$29(D:\Chrome\burpsuite_pro_v1.6.17\bapps\f9bbac8c4acf4aefa4d7dc92a991af2f\Autorize.py:571)
	at org.python.pycode._pyx1.call_function(D:\Chrome\burpsuite_pro_v1.6.17\bapps\f9bbac8c4acf4aefa4d7dc92a991af2f\Autorize.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.actionPerformed$49(D:\Chrome\burpsuite_pro_v1.6.17\bapps\f9bbac8c4acf4aefa4d7dc92a991af2f\Autorize.py:673)
	at org.python.pycode._pyx1.call_function(D:\Chrome\burpsuite_pro_v1.6.17\bapps\f9bbac8c4acf4aefa4d7dc92a991af2f\Autorize.py)

**Comment by johnniesong** [comment]
I check api documents of makeHttpRequest(), the third parameter should be str(requestURL.getProtocol())?

return self._callbacks.makeHttpRequest(self._helpers.buildHttpService(str(requestURL.getHost()), int(requestURL.getPort()), requestURL.getProtocol() == "https"), message)

**Comment by johnniesong** [comment]
I have up-to-date file but get same error.

java.lang.RuntimeException: java.lang.RuntimeException: Extensions should not make HTTP requests in the Swing event dispatch thread
	at burp.my.a(Unknown Source)
	at burp.tyg.makeHttpRequest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:496)
	at org.python.core.PyObject.__call__(PyObject.java:500)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.makeRequest$27(D:\Project_\burp extension\Autorize1.py:539)
	at org.python.pycode._pyx1.call_function(D:\Project_\burp extension\Autorize1.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.checkAuthorization$29(D:\Project_\burp extension\Autorize1.py:591)
	at org.python.pycode._pyx1.call_function(D:\Project_\burp extension\Autorize1.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.actionPerformed$49(D:\Project_\burp extension\Autorize1.py:693)
	at org.python.pycode._pyx1.call_function(D:\Project_\burp extension\Autorize1.py)

**Comment by federicodotta** [comment]
Fixed with commit 355e58da43d42ddbd9c4487375c6707589579df9

**Comment by Quitten** [comment]
Jhon, can you verify it? It is impossible for me to do so right now.

**Comment by johnniesong** [comment]
The bug is fix, thank you.
