### ISSUE TITLE
Autorize Showing Error

### ISSUE THREAD

**Issue by Th3BlackHol3** [Quitten/Autorize#114]
I am using Burp Suite Professional 2020.11 version (Parrot OS), I followed the steps to install Autorize but My burp is not loading Autorize and showing an error. Here is the error:

java.lang.Exception: Failed to open Jython JAR file
	at burp.b4e.<init>(Unknown Source)
	at burp.g50.a(Unknown Source)
	at burp.dz6.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Quitten** [comment]
Seems like you missed step 3 on installation phase: https://github.com/Quitten/Autorize#installation
