### ISSUE TITLE
Burp 1.7.36 jython Standalone 2.7.0 Non-ASCII character in file

### ISSUE THREAD

**Issue by vanquishsecurity** [Quitten/Autorize#27]
Burp 1.7.36 jython Standalone 2.7.0 Non-ASCII character in file

SyntaxError: Non-ASCII character in file '/root/Desktop/burpsuite/Autorize.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

	at org.python.core.Py.SyntaxError(Py.java:198)
	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:105)
	at org.python.core.ParserFacade.parse(ParserFacade.java:190)
	at org.python.core.Py.compile_flags(Py.java:1956)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:527)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.ohg.<init>(Unknown Source)
	at burp.spf.a(Unknown Source)
	at burp.gih.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Quitten** [comment]
Haha love the result :)
all was missing is just the header lines which added at https://github.com/Quitten/Autorize/commit/8e70b16ab2779ca3a3b5d522fdd8a6b9560f2f0b
Let me know if it fixed
