### ISSUE TITLE
non asciis characters in enforcement detector

### ISSUE THREAD

**Issue by zaleoth** [Quitten/Autorize#66]
Hi !

Autorize seems to be allergic to the use of non-ascii (example: "è") char in "enforcement detector" filter (body & full message filter at least). 

Filter text was "Accès interdit".
Here is the python stack (java stack is skipped) obtained and that made me think of an encoding error.

```
	at authorization.authorization$py.checkAuthorization$12(/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py:289)
	at authorization.authorization$py.call_function(/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:187)
	at org.python.core.PyFunction.__call__(PyFunction.java:449)
	at authorization.authorization$py.handle_message$8(/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py:128)
	at authorization.authorization$py.call_function(/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:187)
	at org.python.core.PyFunction.__call__(PyFunction.java:449)
	at org.python.pycode._pyx4.processHttpMessage$3(/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/Autorize.py:37)
	at org.python.pycode._pyx4.call_function(/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/Autorize.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$19.processHttpMessage(Unknown Source)
	at burp.f76.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Traceback (most recent call last):
  File "/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/Autorize.py", line 37, in processHttpMessage
    handle_message(self, toolFlag, messageIsRequest, messageInfo)
  File "/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 128, in handle_message
    checkAuthorization(self, messageInfo,self._helpers.analyzeResponse(messageInfo.getResponse()).getHeaders(),self.doUnauthorizedRequest.isSelected())
  File "/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 271, in checkAuthorization
    impression = checkBypass(self, oldStatusCode,newStatusCode,oldContentLen,newContentLen,EDFilters,requestResponse,self.AndOrType.getSelectedItem())
  File "/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 238, in checkBypass
    auth_enforced = auth_enforced_via_enforcement_detectors(self, filters, requestResponse, andOrEnforcement)
  File "/home/cca/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 156, in auth_enforced_via_enforcement_detectors
    if str(filter).startswith("Status code equals: "):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 34: ordinal not in range(128)

	at org.python.core.codecs.strict_errors(codecs.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[...]
```

And by the way, thanks for this awesome extension...!

**Comment by Quitten** [comment]
Fixed on 3d00ff2599f2500f333655a0ed531006300b8573.
Please verify and comment.

and btw, I am really glad you enjoyed this tool, I recently released another tool for researching postMessage vulnerabilities called [posta](https://github.com/benso-io/posta)

**Comment by zaleoth** [comment]
Hi 

Seems that there still is some problems. But no more error or output is available in Burp extender tab.

Current Symptoms : 
Detection filter containing "è" : no more request is shown in autorize tab (no new line) despite incoming requests.

**Comment by zaleoth** [comment]
`Seems that there still are some problems. But no more error or output is available in Burp extender tab.`

Sorry for that blatant PEBKAC.

This modification fixed the issue. Thanks a lot for the really quick fix.

**Comment by Quitten** [comment]
@zaleoth - You are welcome, happy to help, feel free to open more issues or contribute in case you have any additional features
