### ISSUE TITLE
Issue loading plugin on latest burp

### ISSUE THREAD

**Issue by 0x42424242** [Quitten/Autorize#69]
#### Detail
Trying to load Autorize results in a crash. Obviously we'd just expect it to load as normal. Would be happy to provide any more detail but not much to say at this point. Any questions or debugging you'd like, please ask. 

#### Versions
Latest Autorize code pulled down today (21/06/2021)
jython-standalone-2.7.2.jar
Burp Suite Professional v2021.6.2-8352 (Early Adopter)

#### Stack Trace
```
Traceback (most recent call last):
  File "C:\Users\Censored\Autorize\Autorize.py", line 9, in <module>
    from helpers.initiator import Initiator
  File "C:\Users\Censored\Autorize\helpers\initiator.py", line 14, in <module>
    from threading import Lock
  File "C:\Python27\Lib\threading.py", line 1190, in <module>
    _shutdown = _MainThread()._exitfunc
  File "C:\Python27\Lib\threading.py", line 1082, in __init__
    self._Thread__started.set()
  File "C:\Python27\Lib\threading.py", line 582, in set
    """
  File "C:\Python27\Lib\threading.py", line 286, in __enter__
    return self.__lock.__enter__()
TypeError: __enter__(): expected 1 args; got 0

	at org.python.core.Py.TypeError(Py.java:236)
	at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:213)
	at org.python.core.PyReflectedFunction.throwArgCountError(PyReflectedFunction.java:266)
	at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:323)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:171)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at threading$py.__enter__$22(C:/Python27/Lib/threading.py:286)
	at threading$py.call_function(C:/Python27/Lib/threading.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:416)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.core.ContextGuard.__enter__(ContextGuard.java:17)
	at threading$py.set$46(C:/Python27/Lib/threading.py:585)
	at threading$py.call_function(C:/Python27/Lib/threading.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:416)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at threading$py.__init__$80(C:/Python27/Lib/threading.py:1085)
	at threading$py.call_function(C:/Python27/Lib/threading.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:20)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:2408)
	at org.python.core.PyType.__call__(PyType.java:2389)
	at org.python.core.PyObject.__call__(PyObject.java:446)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at threading$py.f$0(C:/Python27/Lib/threading.py:1321)
	at threading$py.call_function(C:/Python27/Lib/threading.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_first(imp.java:1219)
	at org.python.core.imp.import_module_level(imp.java:1361)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at helpers.initiator$py.f$0(C:/Users/Censored/Autorize/helpers/initiator.py:16)
	at helpers.initiator$py.call_function(C:/Users/Censored/Autorize/helpers/initiator.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromSource(imp.java:583)
	at org.python.core.imp.loadFromSource(imp.java:944)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_logic(imp.java:1278)
	at org.python.core.imp.import_module_level(imp.java:1369)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at org.python.pycode._pyx5.f$0(C:/Users/Censored/Autorize/Autorize.py:11)
	at org.python.pycode._pyx5.call_function(C:/Users/Censored/Autorize/Autorize.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.aa0.<init>(Unknown Source)
	at burp.hfn.a(Unknown Source)
	at burp.bzk.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Quitten** [comment]
Can't reproduce the bug, I would like to know if anyone else having the same issue

**Comment by Quitten** [comment]
Closed due to inactivity.
