### ISSUE TITLE
Bug on "send_request_to_autorize" function

### ISSUE THREAD

**Issue by Th0h0** [Quitten/Autorize#96]
Hello, whenever I send I big number of requests ( more than 30) to Autorize, nothing proceeds/shows up on extension window, and the follows error message is produced in the "Errors" logs:

```
    checkAuthorization(self, newHttpRequestResponsePersisted,self._helpers.analyzeResponse(messageInfo.getResponse()).getHeaders(),self.doUnauthorizedRequest.isSelected())
  File "/Users/thomashouhou/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 302, in checkAuthorization
    newStatusCode = analyzedResponse.getHeaders()[0]
IndexError: index out of range: 0
Unhandled exception in thread started by <function send_request_to_autorize at 0x2>
Traceback (most recent call last):
  File "/Users/thomashouhou/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 191, in send_request_to_autorize
    checkAuthorization(self, newHttpRequestResponsePersisted,self._helpers.analyzeResponse(messageInfo.getResponse()).getHeaders(),self.doUnauthorizedRequest.isSelected())
  File "/Users/thomashouhou/.BurpSuite/bapps/f9bbac8c4acf4aefa4d7dc92a991af2f/authorization/authorization.py", line 302, in checkAuthorization
    newStatusCode = analyzedResponse.getHeaders()[0]
IndexError: index out of range: 0
....
...
....
```

I tried restarting Burp, restarting the extension, unloading and loading it again etc, and still same error.
Would you have any idea on how to fix this ?
Thanks

**Comment by Th0h0** [comment]
I finally understood where this problem came from.
It actually comes from the fact that too many requests are sent at the same time to the application, which then timeouts/blacklists me. Therefore Autorize didnd't receive any HTTP response anymore and couldn't proceed anymore.
To fix such behavior, it would be cool to implement Rate Limiting in Autorize when sending requests to it, so that it wouldn't do more than X requests per sec.
I'm going to work on it and maybe make a PR if it works.
